AWSTemplateFormatVersion: 2010-09-09 ## Got this from cloudformation website
Description: Create a role for us to assume and createa resource we'll have access
# Resources section
Parameters:
  BucketName:
    Type: String
    Default: "sts-fun-bs"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::905315126713:user/sts-machine-user"
              # Service:
              #   - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: 
                  - !Sub "arn:aws:s3:::*"
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"
