#! /usr/bin/env bash
echo "List Newest Buckets"

#aws s3api list-buckets --output table --query Buckets[].Name

aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | .Name'

echo "..."