#!/usr/bin/env bash
# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/index.html#cli-aws-cloudformation

echo "== deploy s3 bucket via CFN"

STACK_NAME="cfn-s3-simple"

echo $STACK_NAME

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--stack-name $STACK_NAME \
--region us-east-1 \